# options
baseURL = "https://cottagepainter.github.io"
languageCode = "en-us"
title = "Cottage Painter"
theme = "cottagepainter"
paginate = 20
canonifyurls = false
pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disableKinds = ["taxonomy", "taxonomyTerm"] 
disqusShortname = "yourdiscussshortname"

[params]
    author = "Currie Carmichael"
    info = "Professional Painter"
    description = "Cottage Painter"
    keywords = "service,ssca,painter,business,painting"
    avatarurl = "images/CottagePainter300.jpg"
    footercontent = ""

    favicon_16 = "/images/CPFavicon16.png"
    favicon_32 = "/images/CPFavicon32.png"

    rtl = false
    math = true
    inverted = false 
    custom_css = ["css/custom.css"]

# social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/cottagepainter/"

# top menu
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Services"
    weight = 2
    url = "/services/"
[[menu.main]]
    name = "References"
    weight = 3
    url = "/references/"
[[menu.main]]
    name = "Contact"
    weight = 4
    url  = "/contact/"
[[menu.main]]
    name = "Resources"
    weight = 5
    url  = "/resources/"

# service menu
[[menu.services]]
	name = "Exterior Painting"
	weight = 1
	url = "/services/exterior-painting"
[[menu.services]]
	name = "Interior Painting"
	weight = 2
	url = "/services/interior-painting"
[[menu.services]]
	name = "Gutter Cleaning"
	weight = 3
	url = "/services/gutter-cleaning"

# resources menu
[[menu.resources]]
	name = "Equipment"
	weight = 1
	url = "/resources/equipment"
[[menu.resources]]
	name = "Spraying"
	weight = 2
	url = "/resources/spraying"
[[menu.resources]]
	name = "Paint"
	weight = 3
	url = "/resources/paint"
[[menu.resources]]
	name = "Glossary"
	weight = 4
	url = "/resources/glossary"
